### ISSUE TITLE
2.0.8 does no longer work!

### ISSUE THREAD

**Issue by muenchris** [etcipnja/MLH#1]
always fires error:

[MLH] Something went wrong: ‘module’ object has no attribute ‘fromtimestamp’

2.0.7 worked fine

THanks
Chris

**Comment by muenchris** [comment]
Correction...It worked a couple days ago...not sure which version.

Is there a way you test in a different branch and keep one with a working version before you commit a new one?

I really love MLH and use it every day to water my farmbed :)

Thanks
Chris

**Comment by etcipnja** [comment]
ugh! I need to pay attention to GitHub messages :)
Yes, this was due to my experiments with intelligent watering. Now it is fixed in 2.2.2

I didn't not realize that farmOS autoupdates all farmware every time you reboot. Now I need to be more careful and test in a separate branch.

Thank you! 
Eugene
